### PR TITLE
Updated profile image

### PR DESCRIPTION
**Pull request by lcrespom**

### CODE REVIEW

**Comment by ifraixedes** [comment]
ups, it needs to be rebase;

@lcrespom can you rebase it, please?

**Comment by lcrespom** [comment]
Sorry, I am not that expert with git not GitHub... how do I rebase?

**Comment by PatrickHeneise** [comment]
Easier is to use the 'Edit' button directly on GitHub https://github.com/BarcelonaJS/BarcelonaJS/blob/master/talks/20160112-sound-synthesis-with-web-audio.md

**Comment by lcrespom** [comment]
Done... I guess / I hope.

**Comment by ifraixedes** [comment]
Merged in #28

**Pull request closed without merging**
